# Generated by Django 2.1.5 on 2019-05-29 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=15)),
                ('status', models.IntegerField(verbose_name=1)),
                ('userid', models.ForeignKey(on_delete='delete', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
