# Generated by Django 2.1.5 on 2019-05-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('post_type', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('bedroom', models.IntegerField(max_length=1)),
                ('bathroom', models.IntegerField(null=True)),
                ('garage', models.CharField(max_length=500)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': 'Vendor'},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='post',
            name='vendor_id',
            field=models.ForeignKey(on_delete='delete', to='data.Vendor'),
        ),
    ]
