# Generated by Django 2.1.5 on 2019-05-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20190531_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='path',
            field=models.FileField(null=True, upload_to='./static/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bathroom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='bedroom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='garage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
