# Generated by Django 2.1.5 on 2019-05-31 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20190531_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='path',
            new_name='bannerfile',
        ),
    ]
