# Generated by Django 2.1.5 on 2019-06-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20190531_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(null=True)),
                ('addedDate', models.DateField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Buyer',
            },
        ),
    ]
