# Generated by Django 2.1.5 on 2019-06-04 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0017_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('blog_type', models.CharField(max_length=100)),
                ('shortDesc', models.CharField(max_length=100, null=True)),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete='delete', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blogfile', models.FileField(null=True, upload_to='./static/img')),
                ('blog', models.ForeignKey(on_delete='delete', to='data.Blog')),
            ],
            options={
                'verbose_name': 'Images',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
