# Generated by Django 2.1.5 on 2019-06-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='longDesc',
            field=models.TextField(default=''),
        ),
    ]
