# Generated by Django 2.1.5 on 2019-06-05 07:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_blog_longdesc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='longDesc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
