# Generated by Django 2.1.5 on 2019-05-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190529_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=100)),
                ('skucode', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('short_description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=1)),
                ('category_id', models.ForeignKey(on_delete='delete', to='data.Category')),
            ],
        ),
    ]
